image: ghcr.io/fxgst/icp-dev-env-azle:8
tasks:
  - before: |
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get update
      sudo apt-get install -q -y libunwind-dev build-essential clang libssl-dev pkg-config podman
      DFX_VERSION=0.18.0 DFXVM_INIT_YES=true sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      source "$HOME/.local/share/dfx/env"
      npm install &
      dfx start --background --clean
      open README.md

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
